apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: app
          image: 678481348986.dkr.ecr.ap-northeast-2.amazonaws.com/projectrp:django
          ports:
            - containerPort: 8080
