apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 4
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: app
          image: 678481348986.dkr.ecr.ap-northeast-2.amazonaws.com/projectrp:django
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  selector:
    app: django-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
